name: Lint Checker

on:
    push:
        branches: [main, master]
    pull_request:
        branch: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
